// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type xdpIn6Addr struct{ In6U struct{ U6Addr8 [16]uint8 } }

type xdpIpv4TrieKey struct {
	Prefixlen uint32
	Addr      uint32
}

type xdpIpv6TrieKey struct {
	Prefixlen uint32
	Addr      xdpIn6Addr
}

type xdpPacketInfo struct {
	SrcIp     uint32
	DstIp     uint32
	SrcIpv6   [4]uint32
	DstIpv6   [4]uint32
	SrcPort   uint16
	DstPort   uint16
	SrcMac    [6]uint8
	DstMac    [6]uint8
	EthProto  uint16
	IpProto   uint16
	PktSize   uint32
	MatchType uint32
}

// loadXdp returns the embedded CollectionSpec for xdp.
func loadXdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp: %w", err)
	}

	return spec, err
}

// loadXdpObjects loads xdp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpObjects
//	*xdpPrograms
//	*xdpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpSpecs struct {
	xdpProgramSpecs
	xdpMapSpecs
}

// xdpSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpProgramSpecs struct {
	XdpProg *ebpf.ProgramSpec `ebpf:"xdp_prog"`
}

// xdpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpMapSpecs struct {
	Events       *ebpf.MapSpec `ebpf:"events"`
	Ipv4CidrTrie *ebpf.MapSpec `ebpf:"ipv4_cidr_trie"`
	Ipv4List     *ebpf.MapSpec `ebpf:"ipv4_list"`
	Ipv6CidrTrie *ebpf.MapSpec `ebpf:"ipv6_cidr_trie"`
	Ipv6List     *ebpf.MapSpec `ebpf:"ipv6_list"`
	MacList      *ebpf.MapSpec `ebpf:"mac_list"`
	Scratch      *ebpf.MapSpec `ebpf:"scratch"`
}

// xdpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpObjects struct {
	xdpPrograms
	xdpMaps
}

func (o *xdpObjects) Close() error {
	return _XdpClose(
		&o.xdpPrograms,
		&o.xdpMaps,
	)
}

// xdpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	Ipv4CidrTrie *ebpf.Map `ebpf:"ipv4_cidr_trie"`
	Ipv4List     *ebpf.Map `ebpf:"ipv4_list"`
	Ipv6CidrTrie *ebpf.Map `ebpf:"ipv6_cidr_trie"`
	Ipv6List     *ebpf.Map `ebpf:"ipv6_list"`
	MacList      *ebpf.Map `ebpf:"mac_list"`
	Scratch      *ebpf.Map `ebpf:"scratch"`
}

func (m *xdpMaps) Close() error {
	return _XdpClose(
		m.Events,
		m.Ipv4CidrTrie,
		m.Ipv4List,
		m.Ipv6CidrTrie,
		m.Ipv6List,
		m.MacList,
		m.Scratch,
	)
}

// xdpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpPrograms struct {
	XdpProg *ebpf.Program `ebpf:"xdp_prog"`
}

func (p *xdpPrograms) Close() error {
	return _XdpClose(
		p.XdpProg,
	)
}

func _XdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_bpfel.o
var _XdpBytes []byte
